### ISSUE TITLE
Can't add someone to current staff if they have any exec committee position, whether current or not

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/cdh-web#374] opened 2021-08-16 15:44 UTC
**Describe the bug**
When trying to add a person to the staff page as interim faculty, if they have ever had any executive committee membership, even if it is not current, they will be listed as past staff instead of current staff.

**Expected behavior**
Current Interim Faculty Director with past exec membership should be listed as current on the staff page.

**Additional context**
possibly related to #232 , but this fix doesn't resolve that problem

**Comment by cvansant** [comment] 2021-08-24 01:46
Thanks for fixing this! Tested with MM (current exec member) and also with Denis Feeney (former exec), whom I made a postdoc for the purpose of this exercise. Only comment is that MM is identified just as "Associate Prof of English" on the exec page, where it would prob be better if she were identified as CDH Faculty Director.

**Comment by cvansant** [comment] 2021-08-24 23:02
1) You're right (obviously!) that this fix doesn't make it possible for an admin to select whether an individual who is exec AND staff appears either on exec, or on staff.
2) However, this fix does make it possible for someone to appear on both pages, which is great! 
3) More to the point, I was able to add Brian Kernighan (current exec member) as current Acting Faculty Director, and he does indeed appear as current staff on the staff page. I changed his dates to being a past exec member and he still showed up as current staff.
4) BUT: now Brian appears as current exec, even though I changed his dates to being past exec. So now the problem appears to be that current staff automatically show up as current exec--kind of the opposite of the problem described above.
5) YET: for the purposes of adding Brian--who in reality is current exec--to both pages, it works!

**Comment by thatbudakguy** [comment] 2021-08-25 16:51
tested and confirmed that Brian still shows as current exec despite having past exec dates. talking with @rlskoeser i think we're OK closing this since the overall goal of adding an exec person to staff has been accomplished, but obviously problems remain. we would rather fold this into #232 and address with all the other person list page problems than delay the release any further.

**Closed by thatbudakguy** 2021-08-25 16:51 UTC
Labels: bug, awaiting testing
