### ISSUE TITLE
Navigation - links disappear after resizing 

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/cdh-web#44] opened 2017-09-19 20:17 UTC
<img width="1302" alt="screen shot 2017-09-19 at 4 16 10 pm" src="https://user-images.githubusercontent.com/17734456/30613404-e9ee0faa-9d55-11e7-8852-1a260bd689d7.png">
 in chrome, the links in navigation disappeared after resizing the window from small back to large.

**Comment by rlskoeser** [comment] 2017-09-20 20:25
I'm not sure what was causing this before, but it doesn't seem to be happening with the latest version.

**Comment by xinyil** [comment] 2017-09-25 14:37
I can still reproduce the issue in chrome and safari: resize the window to mobile and expanded the menu, then resize it back to large.

**Comment by rlskoeser** [comment] 2017-09-26 15:15
I can't duplicate this with current test site in chrome, safari, or firefox.  @bwhicks can you?

**Comment by rlskoeser** [comment] 2017-09-26 15:37
@bwhicks any chance there is an interaction with the javascript that hides the nav on scroll?

**Comment by xinyil** [comment] 2017-09-26 17:13
screen record: https://cdhprinceton.slack.com/files/U2VJ8B3SM/F793QCZM0/cdhweb-nav-issue.mov

**Comment by bwhicks** [comment] 2017-09-26 18:02
@rlskoeser Just noting for Github that I can reproduce this following Xinyi's  steps in Firefox. If the menu is expanded in the mobile frame and you increase the viewport, it also re-expands with logo centered.

**Comment by thatbudakguy** [comment] 2018-08-28 18:37
Can't reproduce this in Firefox with the new nav, so closing. We can open a new issue if a similar bug crops up with the new nav.

**Closed by thatbudakguy** 2018-08-28 18:37 UTC
Labels: tested needs attention
